[package]
name = "lumisync-server"
version = "0.1.0"
edition = "2021"

[dependencies]
analyser.workspace = true
argon2 = "0.5"
axum = "0.7"
axum-extra = { version = "0.9", features = ["typed-header"] }
chrono = { version = "0.4", features = ["serde"] }
jsonwebtoken = "9"
password-hash = { version = "0.5", features = ["getrandom"] }
rumqttc = "0.24"
rustls-native-certs = "0.8"
rustls-pemfile = "2"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serialport = "4"
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "chrono"] }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
toml.workspace = true
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.5", features = ["cors"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }