[package]
name = "lumisync_api"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"] }
time = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["serde"] }
utoipa = { workspace = true, features = ["macros", "time"], optional = true }

[features]
default = []
docs = ["dep:utoipa"]
