[package]
name = "lumisync_embedded"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
heapless = { version = "0.8.0", features = ["serde"] }
embedded-hal = "1"
serde = { version = "1", default-features = false, features = ["derive"] }
